version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - your-network

  your-app:
    image: poekmon-rest-template:latest
    container_name: your-app-container
    ports:
      - "8085:8080"
    networks:
      - your-network
    depends_on:
      - redis

networks:
  your-network:
